// Auto-generated by boneyard vite plugin — do not edit
import { registerBones } from 'boneyard-js/svelte'

import _hero_events from './hero-events.bones.json'
import _hero_posts from './hero-posts.bones.json'
import _test_calendar from './test-calendar.bones.json'

registerBones({
  "hero-events": _hero_events,
  "hero-posts": _hero_posts,
  "test-calendar": _test_calendar,
})
