// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/svelte'

import _hero_posts from './hero-posts.bones.json'
import _hero_events from './hero-events.bones.json'
import _test_calendar from './test-calendar.bones.json'

configureBoneyard({"color":"#e5e5e5","darkColor":"#2a2a2a","animate":"shimmer","shimmerColor":"#ebebeb","darkShimmerColor":"#333333","speed":"2s","shimmerAngle":110})

registerBones({
  "hero-posts": _hero_posts,
  "hero-events": _hero_events,
  "test-calendar": _test_calendar,
})
