// Auto-generated by boneyard vite plugin — do not edit
import { registerBones } from 'boneyard-js/svelte';

import _test_calendar from './test-calendar.bones.json';

registerBones({
	'test-calendar': _test_calendar
});
